Advance operation

In [3]:
import numpy as np
import matplotlib as mpl


In [9]:
sales_data=np.array([
    [1,100,200,400,500],
    [2,300,400,600,800],
    [2,300,400,660,800],
    [2,300,400,680,800],
    [2,300,400,600,800]
])
print(sales_data.shape) 
# printing the size 
print(sales_data[0:3])

(5, 5)
[[  1 100 200 400 500]
 [  2 300 400 600 800]
 [  2 300 400 660 800]]


TOTAL SALES PER YEAR 

In [ ]:
print()