Indexing and Slicing


In [2]:
import numpy as np

1d array


In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing:\n",arr[2:6])
print("basic slicing with step:\n",arr[2:8:2])
print("Negative slicing:\n",arr[-2])

basic slicing:
 [3 4 5 6]
basic slicing with step:
 [3 5 7]
Negative slicing:
 9


2d array


In [11]:
arr2d=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]
                ])
print("Specific element:\n",arr2d[1,2])
print("Entire row:\n",arr2d[1])
print("Entire column:\n",arr2d[:,1])

Specific element:
 7
Entire row:
 [5 6 7 8]
Entire column:
 [ 2  6 10]


Sorting


In [ ]:
unsorted=np.array([9,5,6,8,7,2,3,4,1])
print("one dimensional:\n",np.sort(unsorted))

unsorted2d=np.array([[1,3,2],[5,6,4]])
print("Two dimensional:\n",np.sort(unsorted2d,axis=1))
#0 or else 1 in axis

one dimensional:
 [1 2 3 4 5 6 7 8 9]
Two dimensional:
 [[1 2 3]
 [4 5 6]]


Filtering


In [15]:
num=np.array([1,2,3,4,5,6,7,8,9,10])
evenNum=num[num%2==0]
print(evenNum)

[ 2  4  6  8 10]


Filter with mask


In [17]:
mask=num>5
print(num[mask])

[ 6  7  8  9 10]


Fancy indexing vs np.where()


In [20]:
indice=[0,2,4]
print(num[indice])

whereResult=np.where(num>7)
print(num[whereResult])

[1 3 5]
[ 8  9 10]


In [ ]:
conditionArr=np.where(num>5 , num*2 , num)
print(conditionArr)

[ 1  2  3  4  5 12 14 16 18 20]


this is how it works

In [ ]:
# if num>5:
#     num*2
# else:
#     num

Add data

In [25]:
arr1=np.array([1,2,3 ])
arr2=np.array([4,5,6 ])
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


Array compatibility

In [26]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("Compatibility shapes\n",a.shape==b.shape)

Compatibility shapes
 True


In [ ]:
import numpy as np

org=np.array([[1,2],[3,4],])
newRow=np.array([[5,6]])

withNewRow=np.vstack((org,newRow))
print(withNewRow)

#for horizontal np.hstack

[[1 2]
 [3 4]
 [5 6]]


Delete operation

In [14]:
arr=np.array([1,2,3,4])
delete=np.delete(arr,2)
print(arr)

[1 2 3 4]
