Learning NUMPY


In [1]:
import numpy as np

creating array from list


In [3]:
arr1d=np.array([1,2,3])
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr1d)
print(arr2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


List vs numpy array


In [6]:
pyList=[1,2,3]
print("Multiplication * 2")
nplist=np.array([1,2,3])
print(pyList*2)
print(nplist*2)

Multiplication * 2
[1, 2, 3, 1, 2, 3]
[2 4 6]


Creating array from scratch

In [ ]:
zeros=np.zeros((4,4))
print(zeros)

#() this is a tuple

ones=np.ones((4,4))
print(ones)

#fills the matrix with the given number

full=np.full((4,4),9)
print(full)

#randomly fills the matrices

random=np.random.random((4,4))
print(random)

#sequence

Sequence=np.arange(0,11,2)
print(Sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[0.63748573 0.94882804 0.205248   0.97264172]
 [0.87406221 0.87063669 0.17990796 0.93128333]
 [0.08186547 0.42030786 0.00645702 0.68157073]
 [0.69513641 0.1595453  0.4630754  0.04348455]]
[ 0  2  4  6  8 10]


Vector, matrix and Tensor

In [12]:
vector=np.array([1,2,3])
print(vector)

matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [14]:
arr=np.array([[1,2,3],[4,5,6]])

print("shape:\n",arr.shape)
print("Dimension:\n",arr.ndim)
print("size:\n",arr.size)
print("Data type:\n",arr.dtype)

shape:
 (2, 3)
Dimension:
 2
size:
 6
Data type:
 int64


Array reshaping

In [17]:
arr=np.arange((12))
print(arr)
#generating a 1d array

reshaped=arr.reshape((3,4))
print(reshaped)
#changing the dimensions

flattened=reshaped.flatten()
print(flattened)
#flattens the array

ravel=reshaped.ravel()
print(ravel)
#only shows the view doesnt modify it

transposed=reshaped.T
print(transposed)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
